language: go
go_import_path: github.com/csi-driver/blobfuse-csi-driver

env:
  global:
    - GO111MODULE=off

go:
  - "1.11.4"

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/rexray/gocsi/csc
  - sudo cp test/integration/blobfuse /usr/bin/

script:
  - hack/verify-all.sh
  - go test -covermode=count -coverprofile=profile.cov ./pkg/...
  - make blobfuse
  - make integration-test
  - make blobfuse-windows
